[package]
name = "yogi"
version = "0.1.0"
authors = ["Dan Rammer <hamersaw@bushpath.com>"]

[dependencies]
bson = "0.4"
clap = {version = "2.19", features = ["yaml"]}
mongodb = {version = "0.2", features = ["ssl"]}
proddle = {path = "../"}
rand = "0.3"
time = "0.1"
