[package]
name = "vantage"
version = "0.4.0"
authors = ["Dan Rammer <hamersaw@bushpath.com>"]

[dependencies]
bson = "0.4"
chan = "0.1"
clap = {version = "2.19", features = ["yaml"]}
curl = "0.4"
proddle = {path = "../"}
rand = "0.3"
slog = "1.5"
slog-scope = "0.2"
slog-term = "1.5"
time = "0.1"
